import { useMemo, useState } from 'react';

const filesByFolder={
 'En mi iPad':[{name:'Aplicaciones',kind:'folder',meta:'24 elementos'},{name:'Documentos',kind:'folder',meta:'8 elementos'},{name:'Descargas',kind:'folder',meta:'3 elementos'},{name:'rainOS',kind:'folder',meta:'Sistema'}],
 Documentos:[{name:'Notas.txt',kind:'file',meta:'2 KB'},{name:'Proyecto.rain',kind:'file',meta:'18 KB'}],
 Descargas:[{name:'rainOS-update.pkg',kind:'file',meta:'42 MB'},{name:'wallpaper.png',kind:'file',meta:'3.4 MB'}],
 rainOS:[{name:'Apps',kind:'folder',meta:'Sistema'},{name:'System',kind:'folder',meta:'Sistema'},{name:'Users',kind:'folder',meta:'Sistema'}]
};
const Toolbar=({children})=><div className="system-toolbar">{children}</div>;

export function Files(){
 const [folder,setFolder]=useState('En mi iPad'); const [selected,setSelected]=useState(null); const items=filesByFolder[folder];
 return <div className="system-app files-app"><aside className="system-sidebar files-sidebar"><div className="sidebar-heading">Ubicaciones</div>{Object.keys(filesByFolder).map(x=><button key={x} className={folder===x?'active':''} onClick={()=>{setFolder(x);setSelected(null)}}><span className="sidebar-glyph">{x==='En mi iPad'?'▣':'▰'}</span>{x}</button>)}</aside><main className="system-main files-main"><Toolbar><div><small>Archivos</small><h1>{folder}</h1></div><div className="toolbar-actions"><button>＋</button><button>•••</button></div></Toolbar><div className="system-breadcrumb">En mi iPad {folder!=='En mi iPad'&&`› ${folder}`}</div><div className="files-grid">{items.map(item=><button key={item.name} className={`file-card ${selected===item.name?'selected':''}`} onDoubleClick={()=>setSelected(item.name)} onClick={()=>setSelected(item.name)}><span className={`file-large-icon ${item.kind}`}><i/></span><b>{item.name}</b><small>{item.meta}</small></button>)}</div>{selected&&<div className="selection-bar"><b>{selected}</b><span>Seleccionado</span></div>}</main></div>;
}

export function Notes(){
 const [notes,setNotes]=useState([{id:1,title:'Bienvenido a rainOS',body:'Explora rainOS y personaliza tu experiencia.'},{id:2,title:'Ideas',body:''}]); const [selected,setSelected]=useState(1); const current=notes.find(n=>n.id===selected)||notes[0];
 const update=field=>e=>setNotes(ns=>ns.map(n=>n.id===current.id?{...n,[field]:e.target.value}:n)); const add=()=>{const id=Date.now();setNotes(ns=>[{id,title:'Nueva nota',body:''},...ns]);setSelected(id)};
 return <div className="system-app notes-app"><aside className="system-sidebar notes-sidebar"><Toolbar><div><small>Notas</small><h1>Todas</h1></div><button onClick={add}>＋</button></Toolbar><label className="system-search">⌕<input placeholder="Buscar notas"/></label><div className="notes-list">{notes.map(n=><button key={n.id} className={selected===n.id?'selected':''} onClick={()=>setSelected(n.id)}><b>{n.title||'Sin título'}</b><small>{n.body||'Sin texto'}</small></button>)}</div></aside><main className="note-editor"><div className="editor-top"><span>Actualizado ahora</span><div><button>↗</button><button>•••</button></div></div><input className="note-title" value={current.title} onChange={update('title')} placeholder="Título"/><textarea value={current.body} onChange={update('body')} placeholder="Empieza a escribir..."/><div className="note-floating-tools"><button>𝗕</button><button>𝘐</button><button>☑</button><button>⌁</button></div></main></div>;
}

export function Photos(){
 const photos=useMemo(()=>Array.from({length:24},(_,i)=>({id:i,label:`Foto ${i+1}`,tone:i%8})),[]); const [tab,setTab]=useState('biblioteca'); const [selected,setSelected]=useState(null);
 return <div className="system-app photos-app"><aside className="system-sidebar photos-sidebar"><button className={tab==='biblioteca'?'active':''} onClick={()=>setTab('biblioteca')}>▦<span>Biblioteca</span></button><button className={tab==='para-ti'?'active':''} onClick={()=>setTab('para-ti')}>♡<span>Para ti</span></button><button className={tab==='albumes'?'active':''} onClick={()=>setTab('albumes')}>▣<span>Álbumes</span></button></aside><main className="system-main photos-main"><Toolbar><div><small>Fotos</small><h1>{tab==='biblioteca'?'Biblioteca':tab==='para-ti'?'Para ti':'Álbumes'}</h1></div><button className="glass-action">Seleccionar</button></Toolbar>{tab==='albumes'?<div className="album-cards"><article><div className="album-cover gradient-a"/><b>Recientes</b><small>24 fotos</small></article><article><div className="album-cover gradient-b"/><b>Favoritos</b><small>0 fotos</small></article></div>:<div className="photos-grid">{photos.map(p=><button key={p.id} className={`photo-tile tone-${p.tone} ${selected===p.id?'selected':''}`} onClick={()=>setSelected(p.id)}><span>{p.label}</span></button>)}</div>}</main></div>;
}

export function Safari(){
 const [url,setUrl]=useState('rainos://inicio'); const [tabs,setTabs]=useState([{id:1,title:'Inicio',url:'rainos://inicio'}]); const [activeTab,setActiveTab]=useState(1); const [history,setHistory]=useState([]);
 const navigate=e=>{e.preventDefault();const title=url==='rainos://inicio'?'Inicio':url.replace(/^https?:\/\//,'').slice(0,24);setTabs(ts=>ts.map(t=>t.id===activeTab?{...t,title,url}:t));setHistory(h=>[url,...h].slice(0,10))}; const newTab=()=>{const id=Date.now();setTabs(ts=>[...ts,{id,title:'Inicio',url:'rainos://inicio'}]);setActiveTab(id);setUrl('rainos://inicio')};
 return <div className="system-app safari-app"><aside className="system-sidebar safari-tabs"><Toolbar><div><small>Safari</small><h1>Pestañas</h1></div><button onClick={newTab}>＋</button></Toolbar>{tabs.map(t=><button key={t.id} className={t.id===activeTab?'selected':''} onClick={()=>{setActiveTab(t.id);setUrl(t.url)}}><span className="tab-favicon">◉</span><span>{t.title}</span><i onClick={e=>{e.stopPropagation();if(tabs.length>1){const next=tabs.filter(x=>x.id!==t.id);setTabs(next);if(activeTab===t.id){setActiveTab(next[0].id);setUrl(next[0].url)}}}}>×</i></button>)}</aside><main className="safari-main"><div className="safari-toolbar"><button>‹</button><button>›</button><form onSubmit={navigate}><span>⌕</span><input value={url} onChange={e=>setUrl(e.target.value)} aria-label="Dirección"/></form><button>↻</button><button>↑</button></div><section className="safari-start"><div className="safari-hero"><div className="safari-orb">✧</div><h1>{url==='rainos://inicio'?'Página de inicio':url}</h1><p>Navegación privada y local de rainOS.</p></div><div className="favorites-row"><button>Favoritos</button><button>Lectura</button><button>Historial</button></div>{history.length>0&&<div className="safari-history"><b>Recientes</b>{history.slice(0,5).map((x,i)=><span key={`${x}-${i}`}>{x}</span>)}</div>}</section></main></div>;
}

export function Weather(){
 const [unit,setUnit]=useState('C'); const forecast=[['Hoy','☀','18° / 27°','24°'],['Mañana','◒','19° / 28°','25°'],['Jue','☁','17° / 24°','22°'],['Vie','◔','18° / 25°','23°'],['Sáb','☀','20° / 29°','26°']];
 return <div className="system-app weather-app"><header className="weather-hero"><div><small>Valencia</small><h1>24°</h1><strong>Despejado</strong><p>Máx. 27° · Mín. 18°</p></div><div className="weather-sun">☀</div></header><section className="weather-card"><header><b>PRÓXIMAS HORAS</b><span>Ahora</span></header><div className="hourly">{['20:00|☀|24°','21:00|☾|23°','22:00|☾|22°','23:00|☾|21°'].map(x=>{const [h,i,t]=x.split('|');return <span key={h}>{h}<b>{i}</b>{t}</span>})}</div></section><section className="weather-card"><header><b>PRÓXIMOS DÍAS</b><button onClick={()=>setUnit(unit==='C'?'F':'C')}>°{unit}</button></header>{forecast.map(x=><div className="forecast-row" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small><strong>{x[3]}</strong></div>)}</section></div>;
}
