import { useEffect, useMemo, useState } from 'react';
import { apps, getApp } from './apps/appRegistry.js';
import { loadPreferences, updatePreference } from './system/systemPreferences.js';
import Calculator from './apps/Calculator.jsx'; import Settings from './apps/Settings.jsx'; import Calendar from './apps/Calendar.jsx'; import Mail from './apps/Mail.jsx'; import Messages from './apps/Messages.jsx'; import Music from './apps/Music.jsx'; import Clock from './apps/Clock.jsx'; import AppStore from './apps/AppStore.jsx'; import SetupAssistant from './apps/SetupAssistant.jsx'; import AdditionalSystemApp from './apps/AdditionalSystemApps.jsx';
import { Files, Notes, Photos, Safari, Weather } from './apps/SystemApps.jsx';
import AppIcon from './ui/AppIcon.jsx'; import AppWindow from './ui/AppWindow.jsx'; import ControlCenter from './ui/ControlCenter.jsx'; import Dock from './ui/Dock.jsx'; import StatusBar from './ui/StatusBar.jsx';

const dockIds=['safari','messages','music','settings'];
const additionalSystemAppIds=new Set(['camera','contacts','maps','reminders','freeform','home','shortcuts','findmy','facetime','books','podcasts','tv','tips','voice']);
const appComponents={calculator:Calculator,settings:Settings,calendar:Calendar,mail:Mail,messages:Messages,music:Music,clock:Clock,appstore:AppStore,files:Files,notes:Notes,photos:Photos,safari:Safari,weather:Weather};
function AppContent({app}){const Component=appComponents[app.id];if(Component)return <Component/>;if(additionalSystemAppIds.has(app.id))return <AdditionalSystemApp id={app.id}/>;return <div className="empty-app"><h2>{app.name}</h2><p>La aplicación no está disponible en esta versión de rainOS.</p></div>}

export default function App(){
 const [time,setTime]=useState(new Date()); const [openApps,setOpenApps]=useState([]); const [activeId,setActiveId]=useState(null); const [stageManager,setStageManager]=useState(false); const [appSwitcher,setAppSwitcher]=useState(false); const [controlCenter,setControlCenter]=useState(false); const [library,setLibrary]=useState(false); const [page,setPage]=useState(0); const [prefs,setPrefs]=useState(loadPreferences); const [setup,setSetup]=useState(()=>localStorage.getItem('rainos.setupComplete')!=='true'); const [touchStart,setTouchStart]=useState(null);
 useEffect(()=>{const id=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{const sync=e=>setPrefs(e.detail);window.addEventListener('rainos-preferences',sync);const lib=()=>setLibrary(true);window.addEventListener('rainos-app-library',lib);return()=>{window.removeEventListener('rainos-preferences',sync);window.removeEventListener('rainos-app-library',lib)}},[]);
 useEffect(()=>{document.documentElement.dataset.appearance=prefs.appearance;document.documentElement.style.setProperty('--rainos-glass-strength',String(prefs.liquidGlass/100));document.documentElement.style.setProperty('--glass-strength',String(prefs.liquidGlass/100));document.documentElement.style.setProperty('--rainos-brightness',String(.55+prefs.brightness/180));document.documentElement.classList.toggle('rainos-bold-text',prefs.boldText)},[prefs]);
 useEffect(()=>{const key=e=>{if(e.key==='Escape'){setControlCenter(false);setStageManager(false);setAppSwitcher(false);setLibrary(false)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 const clock=useMemo(()=>time.toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}),[time]); const date=useMemo(()=>time.toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'}),[time]);
 const pages=useMemo(()=>{const out=[];for(let i=0;i<apps.length;i+=16)out.push(apps.slice(i,i+16));return out},[]); const currentPage=pages[page]||[]; const dockApps=dockIds.map(getApp).filter(Boolean);
 const finishSetup=values=>{if(values?.appearance)updatePreference('appearance',values.appearance);if(typeof values?.wifi==='boolean')updatePreference('wifi',values.wifi);if(values?.multitaskingMode)updatePreference('multitaskingMode',values.multitaskingMode);localStorage.setItem('rainos.setupComplete','true');localStorage.setItem('rainos.setupProfile',JSON.stringify(values||{}));setSetup(false)};
 const openApp=app=>{setOpenApps(cur=>cur.some(x=>x.id===app.id)?cur:[...cur,{...app,mode:prefs.multitaskingMode==='fullscreen'?'fullscreen':'window'}]);setActiveId(app.id);setStageManager(false);setAppSwitcher(false);setLibrary(false)};
 const closeApp=id=>{setOpenApps(cur=>cur.filter(x=>x.id!==id));setActiveId(cur=>cur===id?null:cur);setAppSwitcher(cur=>cur)};
 const toggleMode=id=>setOpenApps(cur=>cur.map(x=>x.id===id?{...x,mode:x.mode==='window'?'fullscreen':'window'}:x));
 const focusApp=id=>{setActiveId(id);setStageManager(false);setAppSwitcher(false)};
 const onTouchStart=e=>setTouchStart(e.touches[0].clientX); const onTouchEnd=e=>{if(touchStart==null)return;const dx=e.changedTouches[0].clientX-touchStart;if(Math.abs(dx)>70&&!openApps.length&&!library){setPage(p=>Math.max(0,Math.min(pages.length-1,p+(dx<0?1:-1))))}setTouchStart(null)};
 return <main className="tablet-shell" style={{filter:`brightness(${.55+prefs.brightness/180})`}} onTouchStart={onTouchStart} onTouchEnd={onTouchEnd}>
  <div className="wallpaper"/><StatusBar time={clock} wifi={prefs.wifi} bluetooth={prefs.bluetooth} battery={100} charging={false} title="rainOS"/>
  {!openApps.length&&!library&&!appSwitcher&&<section className="home"><div className="home-date">{date}</div><div className="app-pages"><div className="app-grid">{currentPage.map(app=><AppIcon key={app.id} app={app} onOpen={openApp}/>)}</div></div><div className="page-indicator">{pages.map((_,i)=><button key={i} className={i===page?'active':''} onClick={()=>setPage(i)} aria-label={`Página ${i+1}`}/>)}</div></section>}
  <Dock apps={dockApps} onOpen={openApp} onSwitcher={()=>setAppSwitcher(true)}/>
  <button className="control-handle" onClick={()=>setControlCenter(v=>!v)} aria-label="Abrir Centro de Control">⌄</button>
  {openApps.map(app=>app.id===activeId&&<AppWindow key={app.id} app={app} mode={app.mode} onClose={()=>closeApp(app.id)} onToggleMode={()=>toggleMode(app.id)} onOpenStageManager={()=>setStageManager(true)}><AppContent app={app}/></AppWindow>)}
  {appSwitcher&&<aside className="app-switcher" aria-label="Selector de aplicaciones"><header><div><span>rainOS</span><h2>Aplicaciones abiertas</h2></div><button onClick={()=>setAppSwitcher(false)} aria-label="Cerrar selector">×</button></header><div className="app-switcher-grid">{openApps.length===0?<div className="switcher-empty">No hay aplicaciones abiertas.</div>:openApps.map(app=><article key={app.id} className={activeId===app.id?'active':''}><button className="switcher-preview" onClick={()=>focusApp(app.id)}><span className={`icon-art icon-art-${app.id}`}><span className="icon-symbol">{app.name.slice(0,1)}</span></span><strong>{app.name}</strong></button><button className="switcher-close" onClick={()=>closeApp(app.id)} aria-label={`Cerrar ${app.name}`}>×</button></article>)}</div></aside>}
  {stageManager&&<aside className="stage-manager" aria-label="Organizador Visual"><div className="stage-manager-header"><span>Organizador Visual</span><button onClick={()=>setStageManager(false)}>×</button></div><div className="stage-manager-list">{openApps.length===0?<div className="stage-empty"><b>No hay ventanas abiertas</b><span>Abre una app para añadirla al espacio.</span></div>:openApps.map(app=><button key={app.id} className={`stage-card ${activeId===app.id?'active':''}`} onClick={()=>focusApp(app.id)}><AppIcon app={app} onOpen={()=>focusApp(app.id)} size="small" disabled/><span>{app.name}</span></button>)}</div></aside>}
  {library&&<aside className="app-library"><header><h2>Biblioteca de apps</h2><button onClick={()=>setLibrary(false)}>×</button></header><div className="library-grid">{apps.map(app=><AppIcon key={app.id} app={app} onOpen={openApp}/>)}</div></aside>}
  {controlCenter&&<ControlCenter wifi={prefs.wifi} bluetooth={prefs.bluetooth} brightness={prefs.brightness} sound={prefs.sound} onWifi={()=>updatePreference('wifi',!prefs.wifi)} onBluetooth={()=>updatePreference('bluetooth',!prefs.bluetooth)} onBrightness={v=>updatePreference('brightness',v)} onSound={v=>updatePreference('sound',v)}/>} {setup&&<SetupAssistant onComplete={finishSetup}/>} 
 </main>
}
